name: Deployed Environment Checks

on:
  schedule:
  - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  deployed-env-checks:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Rosetta
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 18
      
    - name: Install NodeJs
      run: npm i node

    - name: Install newman
      run: npm i newman

    - name: Check Testnet
      working-directory: ./test/deployed-environment-test
      run: node data-deployment-test testnet.postman_environment.json

    - name: Check Shelley-QA
      if: always()
      working-directory: ./test/deployed-environment-test
      run: node data-deployment-test shelley-qa.postman_environment.json

    - name: Check Staging
      if: always()
      working-directory: ./test/deployed-environment-test
      run: node data-deployment-test staging.postman_environment.json

    - name: Check Mainnet
      if: always()
      working-directory: ./test/deployed-environment-test
      run: node data-deployment-test mainnet.postman_environment.json

